---
name: Build

on: 
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ldap-utils
          sudo apt-get install -y libsasl2-dev python3-dev libldap2-dev libssl-dev
          pip3 install python-ldap
      - name: Build
        run: ./gha_test.sh
